import openpyxl
import re

PIC_MAP = {
    'aidhiy': 'H AIDI', 'h aidi': 'H AIDI', 'h. aidi': 'H AIDI', 'aidi': 'H AIDI',
    'm. toher': 'M TOHER', 'm toher': 'M TOHER', 'toher': 'M TOHER',
    'm. zaini': 'M ZAINI', 'm zaini': 'M ZAINI', 'zaini': 'M ZAINI',
    'ferryus': 'FERRYUS', 'feryus': 'FERRYUS',
    'm. iqbal': 'M IQBAL', 'm iqbal': 'M IQBAL', 'iqbal': 'M IQBAL',
    'yoga': 'YOGA', 'jhon fm': 'JHON', 'jhon': 'JHON', 'john': 'JHON',
    'amp': 'AMP', 'japa': 'JAPA', 'msw': 'MSW', 'dede': 'DEDE', 'farhan': 'FARHAN', 'majid': 'MAJID'
}

def norm_pic(p):
    if not p: return ''
    p_clean = str(p).strip().lower()
    return PIC_MAP.get(p_clean, str(p).strip().upper())

# Data structure for all 64 WOs from om unit 1.pdf
# Each item: (no, wo_no, job_desc, area, sched, status, pic, subtasks)
# subtasks: list of (subtask_desc, is_done, date, pic_task)

DATA = [
    (1, "WO-100826-0012", "OM EIC Y1 UNIT COMMON COOLING TOWER FAN 1", "COOLING TOWER", "22/08/2026", "IN PROGRESS", "H AIDI", [
        ("INSPECTION FRAME MOTOR", True, "22/08/2026", "H AIDI"),
        ("REGREASING (JIKA DILENGKAPI NIPPLE GREASE)", True, "22/08/2026", "H AIDI"),
        ("INSPECTION BEARING DAN REPLACEMENT (JIKA DIPERLUKAN)", True, "22/08/2026", "H AIDI"),
        ("INSPECTION TAHANAN ISOLASI", True, "22/08/2026", "H AIDI"),
        ("INSPECTION TAHANAN WINDING", True, "22/08/2026", "H AIDI"),
        ("INSPECTION COOLING FAN", True, "22/08/2026", "H AIDI"),
        ("INSPECTION TERMINASI", True, "22/08/2026", "H AIDI"),
        ("INSPECTION KONEKSI GROUNDING SYSTEM", True, "22/08/2026", "H AIDI"),
        ("SOLO RUN", False, "", "")
    ]),
    (2, "WO-100826-0013", "OM EIC Y1 UNIT COMMON COOLING TOWER FAN 2", "COOLING TOWER", "22/08/2026", "IN PROGRESS", "H AIDI", [
        ("INSPECTION FRAME MOTOR", True, "22/08/2026", "H AIDI"),
        ("REGREASING (JIKA DILENGKAPI NIPPLE GREASE)", True, "22/08/2026", "H AIDI"),
        ("INSPECTION BEARING DAN REPLACEMENT (JIKA DIPERLUKAN)", True, "22/08/2026", "H AIDI"),
        ("INSPECTION TAHANAN ISOLASI", True, "22/08/2026", "H AIDI"),
        ("INSPECTION TAHANAN WINDING", True, "22/08/2026", "H AIDI"),
        ("INSPECTION COOLING FAN", True, "22/08/2026", "H AIDI"),
        ("INSPECTION TERMINASI", True, "22/08/2026", "H AIDI"),
        ("INSPECTION KONEKSI GROUNDING SYSTEM", True, "22/08/2026", "H AIDI"),
        ("SOLO RUN", False, "", "")
    ]),
    (3, "WO-100826-0014", "OM EIC Y1 UNIT COMMON MAIN COOLING WATER PUMP 1", "COOLING WATER", "22/08/2026", "IN PROGRESS", "H AIDI", [
        ("INSPECTION FRAME MOTOR", True, "22/08/2026", "H AIDI"),
        ("REGREASING (JIKA DILENGKAPI NIPPLE GREASE)", True, "22/08/2026", "H AIDI"),
        ("INSPECTION TAHANAN WINDING", True, "22/08/2026", "H AIDI"),
        ("INSPECTION TAHANAN ISOLASI", True, "22/08/2026", "H AIDI"),
        ("INSPECTION COOLING FAN", True, "22/08/2026", "H AIDI"),
        ("INSPECTION TERMINASI", True, "22/08/2026", "H AIDI"),
        ("INSPECTION KONEKSI GROUNDING SYSTEM", True, "22/08/2026", "H AIDI"),
        ("SOLO RUN", False, "", ""),
        ("INSPECTION AND CALIBRATION MEASUREMENT DEVICE", False, "", "")
    ]),
    (4, "WO-100826-0015", "OM EIC Y1 UNIT COMMON MAIN COOLING WATER PUMP 2", "COOLING WATER", "22/08/2026", "IN PROGRESS", "H AIDI", [
        ("INSPECTION FRAME MOTOR", True, "22/08/2026", "H AIDI"),
        ("REGREASING (JIKA DILENGKAPI NIPPLE GREASE)", True, "22/08/2026", "H AIDI"),
        ("INSPECTION TAHANAN ISOLASI", True, "22/08/2026", "H AIDI"),
        ("INSPECTION TAHANAN WINDING", True, "22/08/2026", "H AIDI"),
        ("INSPECTION COOLING FAN", True, "22/08/2026", "H AIDI"),
        ("INSPECTION TERMINASI", True, "22/08/2026", "H AIDI"),
        ("INSPECTION KONEKSI GROUNDING SYSTEM", True, "22/08/2026", "H AIDI"),
        ("SOLO RUN", False, "", ""),
        ("INSPECTION AND CALIBRATION MEASUREMENT DEVICE", False, "", "")
    ]),
    (5, "WO-100826-0016", "OM EIC Y1 UNIT COMMON AUXILIARY COOLING WATER PUMP 1", "COOLING WATER", "22/08/2026", "IN PROGRESS", "H AIDI", [
        ("INSPECTION FRAME MOTOR", True, "22/08/2026", "H AIDI"),
        ("INSPECTION BEARING & REPLACEMENT", False, "", ""),
        ("REGREASING (JIKA DILENGKAPI NIPPLE GREASE)", True, "22/08/2026", "H AIDI"),
        ("INSPECTION TAHANAN ISOLASI", True, "22/08/2026", "H AIDI"),
        ("INSPECTION TAHANAN WINDING", True, "22/08/2026", "H AIDI"),
        ("INSPECTION COOLING FAN", False, "", ""),
        ("INSPECTION TERMINASI", True, "22/08/2026", "H AIDI"),
        ("INSPECTION KONEKSI GROUNDING SYSTEM", False, "", ""),
        ("INSPECTION AND CALIBRATION MEASUREMENT DEVICE", False, "", "")
    ]),
    (6, "WO-100826-0017", "OM EIC Y1 UNIT COMMON AUXILIARY COOLING WATER PUMP 2", "COOLING WATER", "22/08/2026", "IN PROGRESS", "H AIDI", [
        ("INSPECTION FRAME MOTOR", True, "22/08/2026", "H AIDI"),
        ("INSPECTION BEARING & REPLACEMENT", True, "22/08/2026", "H AIDI"),
        ("REGREASING (JIKA DILENGKAPI NIPPLE GREASE)", True, "22/08/2026", "H AIDI"),
        ("INSPECTION TAHANAN ISOLASI", True, "22/08/2026", "H AIDI"),
        ("INSPECTION TAHANAN WINDING", True, "22/08/2026", "H AIDI"),
        ("INSPECTION COOLING FAN", True, "22/08/2026", "H AIDI"),
        ("INSPECTION TERMINASI", False, "", ""),
        ("INSPECTION KONEKSI GROUNDING SYSTEM", False, "", ""),
        ("INSPECTION AND CALIBRATION MEASUREMENT DEVICE", False, "", "")
    ]),
    (7, "WO-100826-0160", "OM EIC Y1 UNIT 1 INDUCED DRAUGHT FAN 1", "BOILER", "22/08/2026", "IN PROGRESS", "M TOHER", [
        ("UNIT 1 INDUCED DRAUGHT FAN 1 INLET GATE ACTUATOR MOV 20HNA61AA001", False, "", "AMP"),
        ("UNIT 1 INDUCED DRAUGHT FAN 1 OUTLET GATE ACTUATOR MOV 20HNA71AA001", False, "", "AMP"),
        ("MSW20HNC10-M103:UNIT 1 INDUCED DRAUGHT FAN 1 MOTOR", True, "22/08/2026", "JAPA"),
        ("REPOSISI MOTOR", True, "22/08/2026", "JAPA"),
        ("DISSASEMBLY COVER FAN DAN COVER BEARING SISI DE DAN NDE", True, "22/08/2026", "JAPA"),
        ("INSPEKSI DAN CLEANING BALL BEARING DE DAN NDE (REPLACE BEARING IF NEEDED)", True, "22/08/2026", "JAPA"),
        ("REGREASING BEARING DAN PENGUKURAN TAHANAN ISOLASI", True, "22/08/2026", "JAPA"),
        ("PENGUKURAN TAHANAN BELITAN", True, "22/08/2026", "JAPA"),
        ("ASSEMBLY ALL PART AND REPOSISI MOTOR", True, "22/08/2026", "JAPA"),
        ("UNIT 1 INDUCED DRAUGHT FAN 1 IGV 10HNC01EX001", False, "", "AMP"),
        ("INLET ID FAN 1 PRESSURE TRANSMITTER 10HNA61CP001", False, "", "JAPA"),
        ("INLET PRESSURE ESP PRESSURE TRANSMITTER 10HNA41CP001", False, "", "JAPA"),
        ("OUTLET PRESSURE ESP PRESSURE TRANSMITTER 10HNA41CP002", False, "", "JAPA"),
        ("SOLO RUN", False, "", "MSW")
    ]),
    (8, "WO-100826-0161", "OM EIC Y1 UNIT 1 INDUCED DRAUGHT FAN 2", "BOILER", "22/08/2026", "SCHED-OK", "M TOHER", [
        ("UNIT 1 INDUCED DRAUGHT FAN 2 INLET ACTUATOR MOV 20HNA62AA001", False, "", "AMP"),
        ("UNIT 1 INDUCED DRAUGHT FAN 2 OUTLET ACTUATOR MOV 20HNA72AA001", False, "", "AMP"),
        ("MSW20HNC10-M203:UNIT 1 INDUCED DRAUGHT FAN 2 MOTOR", False, "", "JAPA"),
        ("REPOSISI MOTOR", False, "", "JAPA"),
        ("DISSASEMBLY COVER FAN DAN COVER BEARING SISI DE DAN NDE", False, "", "JAPA"),
        ("INSPEKSI DAN CLEANING BALL BEARING DE DAN NDE (REPLACE BEARING IF NEEDED)", False, "", "JAPA"),
        ("REGREASING BEARING DAN PENGUKURAN TAHANAN ISOLASI", False, "", "JAPA"),
        ("PENGUKURAN TAHANAN BELITAN", False, "", "JAPA"),
        ("ASSEMBLY ALL PART AND REPOSISI MOTOR", False, "", "JAPA"),
        ("UNIT 1 INDUCED DRAUGHT FAN 2 IGV 10HNC01EX002", False, "", "AMP"),
        ("SOLO RUN", False, "", "MSW"),
        ("INLET ID FAN 2 PRESSURE TRANSMITTER 10HNA62CP001", False, "", "JAPA")
    ]),
    (9, "WO-100826-0020", "OM EIC Y1 UNIT 1 PRIMARY AIR FAN 1", "BOILER", "22/08/2026", "IN PROGRESS", "M ZAINI", [
        ("REPOSISI MOTOR", True, "22/08/2026", "JAPA"),
        ("DISSASEMBLY COVER FAN DAN COVER BEARING SISI DE DAN NDE", True, "22/08/2026", "JAPA"),
        ("INSPEKSI DAN CLEANING BALL BEARING DE DAN NDE", True, "22/08/2026", "JAPA"),
        ("REPLACE BEARING IF NEEDED", True, "22/08/2026", "JAPA"),
        ("REGREASING BEARING DAN PENGUKURAN TAHANAN ISOLASI", True, "22/08/2026", "JAPA"),
        ("PENGUKURAN TAHANAN BELITAN", True, "22/08/2026", "JAPA"),
        ("ASSEMBLY ALL PART AND REPOSISI MOTOR", True, "22/08/2026", "JAPA"),
        ("UNIT 1 PRIMARY AIR FAN 1 IGV", False, "", "MSW"),
        ("UNIT 1 PRIMARY AIR FAN 1 OUTLET MOV", False, "", "MSW"),
        ("PA FAN 1 OUTLET PRESSURE TRANSMITTER 10HLB03CP001", True, "22/08/2026", "JAPA")
    ]),
    (10, "WO-100826-0021", "OM EIC Y1 UNIT 1 PRIMARY AIR FAN 1 LUBE OIL SYSTEM", "BOILER", "22/08/2026", "IN PROGRESS", "H AIDI", [
        ("MSW20HLN20-M101:UNIT 1 PRIMARY AIR FAN 1 LUBE OIL PUMP 1 MOTOR (STAND BY)", True, "22/08/2026", "H AIDI"),
        ("MSW20HLN20-M102:UNIT 1 PRIMARY AIR FAN 1 LUBE OIL PUMP 2 MOTOR (MAIN)", True, "22/08/2026", "H AIDI"),
        ("20HLB01CP104: LO HEADER PRESSURE LOW ALARM FOR PA FAN-1", True, "22/08/2026", "H AIDI"),
        ("20HLB01CP103: PRESSURE SWITCH TO START PERMISSIVE FOR PA FAN-1 START", True, "22/08/2026", "H AIDI"),
        ("20HLB01CP102: PRESSURE SWITCH TO START LO PA FAN-1 STANDBY PUMP", False, "", ""),
        ("20HLB01CP101: DP SWITCH ACROSS LO TANK FOR PA FAN-1", False, "", "")
    ]),
    (11, "WO-100826-0022", "OM EIC Y1 UNIT 1 PRIMARY AIR FAN 2", "BOILER", "22/08/2026", "IN PROGRESS", "M ZAINI", [
        ("REPOSISI MOTOR", True, "22/08/2026", "M ZAINI"),
        ("DISSASEMBLY COVER FAN DAN COVER BEARING SISI DE DAN NDE", True, "22/08/2026", "M ZAINI"),
        ("INSPEKSI DAN CLEANING BALL BEARING DE DAN NDE", True, "22/08/2026", "M ZAINI"),
        ("REPLACE BEARING IF NEEDED", True, "22/08/2026", "M ZAINI"),
        ("REGREASING BEARING DAN PENGUKURAN TAHANAN ISOLASI", True, "22/08/2026", "M ZAINI"),
        ("PENGUKURAN TAHANAN BELITAN", True, "22/08/2026", "M ZAINI"),
        ("ASSEMBLY ALL PART AND REPOSISI MOTOR", True, "22/08/2026", "M ZAINI"),
        ("UNIT 1 PRIMARY AIR FAN 2 IGV", False, "", ""),
        ("MSW20HLB20AA202:UNIT 1 PRIMARY AIR FAN 2 OUTLET MOV", False, "", ""),
        ("PA FAN 2 OUTLET PRESSURE TRANSMITTER 10HLB04CP001", True, "22/08/2026", "M ZAINI")
    ]),
    (12, "WO-100826-0023", "OM EIC Y1 UNIT 1 PRIMARY AIR FAN 2 LUBE OIL SYSTEM", "BOILER", "22/08/2026", "IN PROGRESS", "H AIDI", [
        ("MSW20HLN20-M201:UNIT 1 PRIMARY AIR FAN 2 LUBE OIL PUMP 1 MOTOR (STAND BY)", True, "22/08/2026", "H AIDI"),
        ("MSW20HLN20-M202:UNIT 1 PRIMARY AIR FAN 2 LUBE OIL PUMP 2 MOTOR (MAIN)", True, "22/08/2026", "H AIDI"),
        ("20HLB02CP104: LO HEADER PRESSURE LOW ALARM FOR PA FAN-2", True, "22/08/2026", "H AIDI"),
        ("20HLB02CP103: PRESSURE SWITCH TO START PERMISSIVE FOR PA FAN-2 START", True, "22/08/2026", "H AIDI"),
        ("20HLB02CP102: PRESSURE SWITCH TO START LO PA FAN-2 STANDBY PUMP", True, "22/08/2026", "H AIDI"),
        ("MSW20HLN20CL201:UNIT 1 PRIMARY AIR FAN 2 LUBE OIL TANK LEVEL SWITCH", False, "", "")
    ]),
    (13, "WO-100826-0024", "OM EIC Y1 UNIT 1 SECONDARY AIR FAN 1", "BOILER", "22/08/2026", "IN PROGRESS", "M ZAINI", [
        ("REPOSISI MOTOR", True, "22/08/2026", "M ZAINI"),
        ("DISSASEMBLY COVER FAN DAN COVER BEARING SISI DE DAN NDE", True, "22/08/2026", "M ZAINI"),
        ("INSPEKSI DAN CLEANING BALL BEARING DE DAN NDE", True, "22/08/2026", "M ZAINI"),
        ("REPLACE BEARING IF NEEDED", True, "22/08/2026", "M ZAINI"),
        ("REGREASING BEARING DAN PENGUKURAN TAHANAN ISOLASI", True, "22/08/2026", "M ZAINI"),
        ("PENGUKURAN TAHANAN BELITAN", True, "22/08/2026", "M ZAINI"),
        ("ASSEMBLY ALL PART AND REPOSISI MOTOR", True, "22/08/2026", "M ZAINI"),
        ("UNIT 1 SECONDARY AIR FAN 1 OUTLET MOV", False, "", ""),
        ("SA FAN 1 OUTLET PRESSURE TRANSMITTER 10HLB01CP001", False, "", ""),
        ("UNIT 1 SECONDARY AIR FAN 1 IGV SA FAN 1 20HLB01EX001", False, "", "")
    ]),
    (14, "WO-100826-0025", "OM EIC Y1 UNIT 1 SECONDARY AIR FAN 1 LUBE OIL SYSTEM", "BOILER", "22/08/2026", "SCHED-OK", "H AIDI", [
        ("MSW20HLN10-M101:UNIT 1 SECONDARY AIR FAN 1 LUBE OIL PUMP 1 MOTOR (STAND BY)", False, "", "H AIDI"),
        ("MSW20HLN10-M102:UNIT 1 SECONDARY AIR FAN 1 LUBE OIL PUMP 2 MOTOR (MAIN)", False, "", "H AIDI"),
        ("20HLB02CP101: DP SWITCH ACROSS LO TANK FOR SA FAN-1", False, "", ""),
        ("20HLB05CP104: LO HEADER PRESSURE LOW ALARM FOR SA FAN-1", False, "", ""),
        ("20HLB05CP103: PRESSURE SWITCH TO START PERMISSIVE FOR SA FAN-1 START", False, "", ""),
        ("20HLB05CP102: PRESSURE SWITCH TO START LO SA FAN-1 STANDBY PUMP", False, "", ""),
        ("20HLB05CP101: DP SWITCH ACROSS LO TANK FOR SA FAN-1", False, "", "")
    ]),
    (15, "WO-100826-0026", "OM EIC Y1 UNIT 1 SECONDARY AIR FAN 2", "BOILER", "22/08/2026", "IN PROGRESS", "M ZAINI", [
        ("REPOSISI MOTOR", True, "22/08/2026", "M ZAINI"),
        ("DISSASEMBLY COVER FAN DAN COVER BEARING SISI DE DAN NDE", True, "22/08/2026", "M ZAINI"),
        ("INSPEKSI DAN CLEANING BALL BEARING DE DAN NDE", True, "22/08/2026", "M ZAINI"),
        ("REPLACE BEARING IF NEEDED", True, "22/08/2026", "M ZAINI"),
        ("REGREASING BEARING DAN PENGUKURAN TAHANAN ISOLASI", True, "22/08/2026", "M ZAINI"),
        ("PENGUKURAN TAHANAN BELITAN", True, "22/08/2026", "M ZAINI"),
        ("ASSEMBLY ALL PART AND REPOSISI MOTOR", True, "22/08/2026", "M ZAINI"),
        ("UNIT 1 SECONDARY AIR FAN 2 OUTLET MOV", False, "", ""),
        ("UNIT 1 IGV SA FAN 2 10HLB01EX001", False, "", ""),
        ("SA FAN 2 OUTLET PRESSURE TRANSMITTER 10HLB02CP001", False, "", "")
    ]),
    (16, "WO-100826-0027", "OM EIC Y1 UNIT 1 SECONDARY AIR FAN 2 LUBE OIL SYSTEM", "BOILER", "22/08/2026", "SCHED-OK", "JHON", [
        ("MSW20HLN10-M201:UNIT 1 SECONDARY AIR FAN 2 LUBE OIL PUMP 1 MOTOR (STAND BY)", False, "", "JHON"),
        ("MSW20HLN10-M202:UNIT 1 SECONDARY AIR FAN 2 LUBE OIL PUMP 2 MOTOR (MAIN)", False, "", "JHON"),
        ("20HLB06CP104: LO HEADER PRESSURE LOW ALARM FOR SA FAN-2", False, "", ""),
        ("20HLB06CP103: PRESSURE SWITCH TO START PERMISSIVE FOR SA FAN-2 START", False, "", ""),
        ("20HLB06CP102: PRESSURE SWITCH TO START LO SA FAN-2 STANDBY PUMP", False, "", ""),
        ("20HLB06CP101: DP SWITCH ACROSS LO TANK FOR SA FAN-2", False, "", "")
    ]),
    (17, "WO-100826-0028", "OM EIC Y1 UNIT 1 COAL FEEDER NO 1", "COAL HANDLING", "22/08/2026", "IN PROGRESS", "H AIDI", [
        ("INSPECTION FRAME MOTOR DRAG CHAIN", True, "22/08/2026", "H AIDI"),
        ("REGREASING (JIKA DILENGKAPI NIPPLE GREASE)", True, "22/08/2026", "H AIDI"),
        ("INSPECTION TAHANAN ISOLASI", True, "22/08/2026", "H AIDI"),
        ("INSPECTION COOLING FAN", True, "22/08/2026", "H AIDI"),
        ("INSPECTION TERMINASI", True, "22/08/2026", "H AIDI"),
        ("INSPECTION KONEKSI GROUNDING SYSTEM", True, "22/08/2026", "H AIDI"),
        ("INSPECTION FRAME MOTOR ROTARY AIR LOCK", True, "22/08/2026", "H AIDI"),
        ("REGREASING (JIKA DILENGKAPI NIPPLE GREASE)", True, "22/08/2026", "H AIDI"),
        ("INSPECTION TAHANAN ISOLASI", True, "22/08/2026", "H AIDI"),
        ("INSPECTION COOLING FAN", True, "22/08/2026", "H AIDI"),
        ("INSPECTION TERMINASI", True, "22/08/2026", "H AIDI"),
        ("INSPECTION KONEKSI GROUNDING SYSTEM", True, "22/08/2026", "H AIDI"),
        ("INSPECTION OF MFT ACTUATOR 10HHE11AA01", False, "", "AMP")
    ]),
    (18, "WO-100826-0029", "OM EIC Y1 UNIT 1 COAL FEEDER NO 2", "COAL HANDLING", "22/08/2026", "IN PROGRESS", "H AIDI", [
        ("INSPECTION FRAME MOTOR DRAG CHAIN", True, "22/08/2026", "H AIDI"),
        ("REGREASING (JIKA DILENGKAPI NIPPLE GREASE)", True, "22/08/2026", "H AIDI"),
        ("INSPECTION TAHANAN ISOLASI", True, "22/08/2026", "H AIDI"),
        ("INSPECTION COOLING FAN", True, "22/08/2026", "H AIDI"),
        ("INSPECTION TERMINASI", True, "22/08/2026", "H AIDI"),
        ("INSPECTION KONEKSI GROUNDING SYSTEM", True, "22/08/2026", "H AIDI"),
        ("INSPECTION FRAME MOTOR ROTARY AIR LOCK", True, "22/08/2026", "H AIDI"),
        ("REGREASING (JIKA DILENGKAPI NIPPLE GREASE)", True, "22/08/2026", "H AIDI"),
        ("INSPECTION TAHANAN ISOLASI", True, "22/08/2026", "H AIDI"),
        ("INSPECTION COOLING FAN", True, "22/08/2026", "H AIDI"),
        ("INSPECTION TERMINASI", True, "22/08/2026", "H AIDI"),
        ("INSPECTION KONEKSI GROUNDING SYSTEM", True, "22/08/2026", "H AIDI"),
        ("INSPECTION OF MFT ACTUATOR 10HHE12AA01", False, "", "AMP")
    ]),
    (19, "WO-100826-0030", "OM EIC Y1 UNIT 1 LDO START-UP BURNER 1", "BOILER", "22/08/2026", "IN PROGRESS", "JHON", [
        ("INSPECTION OF IGNITER GUN", True, "22/08/2026", "MSW"),
        ("INSPECTION OF START UP BURNER SKID DEVICE", True, "22/08/2026", "MSW"),
        ("LDO PRESSURE BEFORE MTV SWITCH 10HJF11CP301", False, "", "MSW"),
        ("ATOM AIR INLET PRESSURE LOW SWITCH 10HJN11CP301", False, "", "MSW"),
        ("LDO PRESSURE LOW TRIP FOR SUB 1 SWITCH 10HJF11CP302", False, "", "MSW"),
        ("ATOM AIR PRESSURE LOW TRIP FOR SUB 1 SWITCH 10HJN11CP302", False, "", "MSW"),
        ("LDO PRESSURE HIGH TRIP FOR SUB 1 SWITCH 10HJF11CP303", False, "", "MSW"),
        ("SCANNER AIR PRESSURE OK 1 SWITCH 10HJG69CP301", False, "", "MSW"),
        ("SCANNER AIR PRESSURE OK 2 SWITCH 10HJG69CP302", False, "", "MSW"),
        ("ACTUATOR SKID BURNER MAIN LDO LINE CONTROL VALVE", False, "", "MSW"),
        ("ACTUATOR SKID BURNER 1 LDO LINE CONTROL VALVE", False, "", "MSW"),
        ("ACTUATOR SKID BURNER 1 ATOMISING AIR LINE CONTROL VALVE", False, "", "MSW"),
        ("ACTUATOR SUB BURNER 1 VALVE 10HJN11AA003", False, "", "AMP"),
        ("ACTUATOR SKID BURNER 1 ATOM AIR ISOLATION VALVE", False, "", "MSW"),
        ("ACTUATOR SKID BURNER 1 LDO ISOLATION VALVE", False, "", "MSW"),
        ("ACTUATOR SKID BURNER 1 SCAVENGING VALVE", False, "", "MSW"),
        ("ATOM AIR PRESSURE AFTER SUB 1 TRANSMITTER 10HJN11CP001", False, "", "JAPA"),
        ("LDO PRESS AFTER SUB1 FVC TRANSMITTER 10HJF11CP001", False, "", "JAPA")
    ]),
    (20, "WO-100826-0031", "OM EIC Y1 UNIT 1 LDO START-UP BURNER 2", "BOILER", "22/08/2026", "SCHED-OK", "JHON", [
        ("INSPECTION OF IGNITER GUN", False, "", "MSW"),
        ("INSPECTION OF START UP BURNER SKID DEVICE", False, "", "MSW"),
        ("LDO PRESSURE LOW TRIP FOR SUB 2 SWITCH 10HJF12CP302", False, "", "MSW"),
        ("ATOM AIR PRESSURE LOW TRIP FOR SUB 2 SWITCH 10HJN12CP302", False, "", "MSW"),
        ("LDO PRESSURE HIGH TRIP FOR SUB 2 SWITCH 10HJF12CP303", False, "", "MSW"),
        ("ATOM AIR PRESSURE AFTER SUB 2 TRANSMITTER 10HJN12CP001", False, "", "JAPA"),
        ("LDO PRESS AFTER SUB2 FCV TRANSMITTER 10HJF12CP001", False, "", "JAPA"),
        ("ACTUATOR SKID BURNER 2 LDO LINE CONTROL VALVE", False, "", "MSW"),
        ("ACTUATOR SKID BURNER 2 ATOMISING AIR LINE CONTROL VALVE", False, "", "MSW"),
        ("ACTUATOR SKID BURNER 2 ATOM AIR ISOLATION VALVE", False, "", "MSW"),
        ("ACTUATOR SKID BURNER 2 LDO ISOLATION VALVE", False, "", "MSW"),
        ("ACTUATOR SKID BURNER 2 SCAVENGING VALVE", False, "", "MSW"),
        ("ACTUATOR SUB BURNER 2 VALVE 10HJN12AA003", False, "", "AMP")
    ]),
    (21, "WO-100826-0032", "OM EIC Y1 UNIT 1 SEALPOT BLOWER NO 1", "BOILER", "22/08/2026", "FINISH", "FERRYUS", [
        ("INSPECTION FRAME MOTOR", True, "22/08/2026", "JAPA"),
        ("REGREASING (JIKA DILENGKAPI NIPPLE GREASE)", True, "22/08/2026", "JAPA"),
        ("PENGGANTIAN BEARING (JIKA DIPERLUKAN)", True, "22/08/2026", "JAPA"),
        ("INSPECTION TAHANAN ISOLASI", True, "22/08/2026", "JAPA"),
        ("INSPECTION COOLING FAN", True, "22/08/2026", "JAPA"),
        ("INSPECTION TERMINASI", True, "22/08/2026", "JAPA"),
        ("INSPECTION KONEKSI GROUNDING SYSTEM", True, "22/08/2026", "JAPA"),
        ("SEALPOT BLOWER PRESS OUTLET TRANSMITTER 10HLB41CP001", True, "22/08/2026", "JAPA"),
        ("P&S BLOWER PRESS OUTLET TRANSMITTER 10QEB20CP001", True, "22/08/2026", "JAPA")
    ]),
    (22, "WO-100826-0033", "OM EIC Y1 UNIT 1 SEALPOT BLOWER NO 2", "BOILER", "22/08/2026", "FINISH", "FERRYUS", [
        ("INSPECTION FRAME MOTOR", True, "22/08/2026", "FERRYUS"),
        ("REGREASING (JIKA DILENGKAPI NIPPLE GREASE)", True, "22/08/2026", "FERRYUS"),
        ("PENGGANTIAN BEARING", True, "22/08/2026", "FERRYUS"),
        ("INSPECTION TAHANAN ISOLASI", True, "22/08/2026", "FERRYUS"),
        ("INSPECTION COOLING FAN", True, "22/08/2026", "FERRYUS"),
        ("INSPECTION TERMINASI", True, "22/08/2026", "FERRYUS"),
        ("INSPECTION KONEKSI GROUNDING SYSTEM", True, "22/08/2026", "FERRYUS")
    ]),
    (23, "WO-100826-0034", "OM EIC Y1 UNIT 1 ELECTROSTATIC PRECIPITATOR 1-6", "ESP", "22/08/2026", "IN PROGRESS", "M IQBAL", [
        ("MSW20HDE10-M101:UNIT 1 ESP RAPPING MOTOR (GDRM)", True, "22/08/2026", "JAPA"),
        ("MSW20HDE10-M102:UNIT 1 ESP RAPPING MOTOR (CERM-1)", True, "22/08/2026", "JAPA"),
        ("MSW20HDE10-M103:UNIT 1 ESP RAPPING MOTOR (CERM-2)", True, "22/08/2026", "JAPA"),
        ("MSW20HDE10-M104:UNIT 1 ESP RAPPING MOTOR (CERM-3)", True, "22/08/2026", "JAPA"),
        ("MSW20HDE10-M105:UNIT 1 ESP RAPPING MOTOR (CERM-4)", True, "22/08/2026", "JAPA"),
        ("MSW20HDE10-M106:UNIT 1 ESP RAPPING MOTOR (CERM-5)", False, "", "JAPA"),
        ("MSW20HDE10-M107:UNIT 1 ESP RAPPING MOTOR (CERM-6)", False, "", "JAPA"),
        ("MSW20HDE10-M108:UNIT 1 ESP RAPPING MOTOR (EERM-1)", False, "", "JAPA"),
        ("MSW20HDE10-M109:UNIT 1 ESP RAPPING MOTOR (EERM-2)", False, "", "JAPA"),
        ("MSW20HDE10-M110:UNIT 1 ESP RAPPING MOTOR (EERM-3)", False, "", "JAPA"),
        ("MSW20HDE10-M120:UNIT 1 ESP RAPPING MOTOR (EERM-4)", False, "", "JAPA"),
        ("MSW20HDE10-M130:UNIT 1 ESP RAPPING MOTOR (EERM-5)", False, "", "JAPA"),
        ("MSW20HDE10-M140:UNIT 1 ESP RAPPING MOTOR (EERM-6)", False, "", "JAPA"),
        ("UNIT 1 ESP TRAFO 1 (GENERAL CLEANING, INSPEKSI, IR TEST)", False, "", "JAPA"),
        ("UNIT 1 ESP TRAFO 2 (GENERAL CLEANING, INSPEKSI, IR TEST)", False, "", "JAPA"),
        ("UNIT 1 ESP TRAFO 3 (GENERAL CLEANING, INSPEKSI, IR TEST)", False, "", "JAPA"),
        ("UNIT 1 ESP TRAFO 4 (GENERAL CLEANING, INSPEKSI, IR TEST)", False, "", "JAPA"),
        ("UNIT 1 ESP TRAFO 5 (GENERAL CLEANING, INSPEKSI, IR TEST)", False, "", "JAPA"),
        ("UNIT 1 ESP TRAFO 6 (GENERAL CLEANING, INSPEKSI, IR TEST)", False, "", "JAPA")
    ]),
    (24, "WO-100826-0035", "OM EIC Y1 UNIT 1 BOILER FEED PUMP 1", "TURBINE", "22/08/2026", "IN PROGRESS", "YOGA", [
        ("INSPECTION FRAME MOTOR", True, "22/08/2026", "JAPA"),
        ("REGREASING (JIKA DILENGKAPI NIPPLE GREASE)", True, "22/08/2026", "JAPA"),
        ("INSPECTION BEARING DAN REPLACEMENT (JIKA DIPERLUKAN)", True, "22/08/2026", "JAPA"),
        ("INSPECTION TAHANAN ISOLASI", True, "22/08/2026", "JAPA"),
        ("INSPECTION TAHANAN WINDING", True, "22/08/2026", "JAPA"),
        ("INSPECTION COOLING FAN", True, "22/08/2026", "JAPA"),
        ("INSPECTION TERMINASI", True, "22/08/2026", "JAPA"),
        ("INSPECTION KONEKSI GROUNDING SYSTEM", False, "", "JAPA"),
        ("MSW20LAC10-M101:MOV DISCHARGE BFP-1", False, "", "MSW"),
        ("MSW20LAC10AA104:UNIT 1 BOILER FEED PUMP 1 VALVE FOR PRESSURE DIFFERENTIAL SWITCH", False, "", "MSW"),
        ("MSW20LAC10AA105:UNIT 1 BOILER FEED PUMP 1 VALVE FOR PRESSURE DIFFERENTIAL SWITCH", False, "", "MSW"),
        ("MSW20LAC10CG101:UNIT 1 BOILER FEED PUMP 1 LIMIT SWITCH", False, "", "MSW"),
        ("20LAC10CP101:UNIT 1 BOILER FEED PUMP 1 PRESSURE DIFFERENTIAL SWITCH", False, "", "MSW"),
        ("MSW20LAC10CT101:UNIT 1 BOILER FEED PUMP 1 R PHASE WDG TEMPERATURE", False, "", "MSW"),
        ("MSW20LAC10CT102:UNIT 1 BOILER FEED PUMP 1 B PHASE WDG TEMPERATURE", False, "", "MSW"),
        ("MSW20LAC10CT103:UNIT 1 BOILER FEED PUMP 1 B PHASE WDG TEMPERATURE", False, "", "MSW"),
        ("MSW20LAC10CT104:UNIT 1 BOILER FEED PUMP 1 B NDE MOTOR BEARING TEMPERATURE", False, "", "MSW"),
        ("MSW20LAC10CT105:UNIT 1 BOILER FEED PUMP 1 B NDE MOTOR BEARING TEMPERATURE", False, "", "MSW"),
        ("MSW20LAC10CT106:UNIT 1 BOILER FEED PUMP 1 B NDE PUMP BEARING TEMPERATURE", False, "", "MSW"),
        ("MSW20LAC10CT107:UNIT 1 BOILER FEED PUMP 1 B NDE PUMP BEARING TEMPERATURE", False, "", "MSW"),
        ("MSW20LAC10GH101:UNIT 1 BOILER FEED PUMP 1 FCMA PANEL", False, "", "MSW")
    ]),
    (25, "WO-100826-0036", "OM EIC Y1 UNIT 1 BOILER FEED PUMP 2", "TURBINE", "22/08/2026", "IN PROGRESS", "YOGA", [
        ("INSPECTION FRAME MOTOR", True, "22/08/2026", "JAPA"),
        ("REGREASING (JIKA DILENGKAPI NIPPLE GREASE)", True, "22/08/2026", "JAPA"),
        ("INSPECTION BEARING DAN REPLACEMENT (JIKA DIPERLUKAN)", True, "22/08/2026", "JAPA"),
        ("INSPECTION TAHANAN ISOLASI", True, "22/08/2026", "JAPA"),
        ("INSPECTION TAHANAN WINDING", True, "22/08/2026", "JAPA"),
        ("INSPECTION COOLING FAN", True, "22/08/2026", "JAPA"),
        ("INSPECTION TERMINASI", True, "22/08/2026", "JAPA"),
        ("INSPECTION KONEKSI GROUNDING SYSTEM", False, "", "MSW"),
        ("MSW20LAC10-M201:MOV DISCHARGE BFP-2", False, "", "MSW"),
        ("MSW20LAC10AA204:UNIT 1 BOILER FEED PUMP 2 VALVE FOR PRESSURE DIFFERENTIAL SWITCH", False, "", "MSW"),
        ("MSW20LAC10AA205:UNIT 1 BOILER FEED PUMP 2 VALVE FOR PRESSURE DIFFERENTIAL SWITCH", False, "", "MSW"),
        ("MSW20LAC10CG201:UNIT 1 BOILER FEED PUMP 2 LIMIT SWITCH", False, "", "MSW"),
        ("MSW20LAC10CP201:UNIT 1 BOILER FEED PUMP 2 PRESSURE DIFFERENTIAL SWITCH", False, "", "MSW"),
        ("MSW20LAC10CT201:UNIT 1 BOILER FEED PUMP 2 R PHASE WDG TEMPERATURE", False, "", "MSW"),
        ("MSW20LAC10CT202:UNIT 1 BOILER FEED PUMP 2 B PHASE WDG TEMPERATURE", False, "", "MSW"),
        ("MSW20LAC10CT203:UNIT 1 BOILER FEED PUMP 2 B PHASE WDG TEMPERATURE", False, "", "MSW"),
        ("MSW20LAC10CT204:UNIT 1 BOILER FEED PUMP 2 B NDE MOTOR BEARING TEMPERATURE", False, "", "MSW"),
        ("MSW20LAC10CT205:UNIT 1 BOILER FEED PUMP 2 B NDE MOTOR BEARING TEMPERATURE", False, "", "MSW"),
        ("MSW20LAC10CT206:UNIT 1 BOILER FEED PUMP 2 B NDE PUMP BEARING TEMPERATURE", False, "", "MSW"),
        ("MSW20LAC10CT207:UNIT 1 BOILER FEED PUMP 2 B NDE PUMP BEARING TEMPERATURE", False, "", "MSW"),
        ("MSW20LAC10GH201:UNIT 1 BOILER FEED PUMP 2 FCMA PANEL", False, "", "MSW")
    ]),
    (26, "WO-100826-0037", "OM EIC Y1 UNIT 1 FEED WATER LINE", "FEED WATER", "22/08/2026", "IN PROGRESS", "M TOHER", [
        ("UNIT 1 FEED WATER INLET ECONOMIZER MOTORIZED VALVE MOTOR 100% 10LAB30AA220", True, "22/08/2026", "AMP"),
        ("UNIT 1 FEED WATER INLET ECONOMIZER MOTORIZED VALVE ISOLATION VALVE", True, "22/08/2026", "AMP"),
        ("UNIT 1 FEED WATER INLET ECONOMIZER MOTORIZED VALVE MOTOR 30% 10LAB30AA210", True, "22/08/2026", "AMP"),
        ("UNIT 1 FEED WATER INLET ECONOMIZER MOTORIZED VALVE ISOLATION VALVE", False, "", "AMP"),
        ("ACTUATOR BFP SPRAY LINE (FEED WATER) TO DEAERATOR PRDS I/L CV 10LAE10AA210", False, "", "AMP"),
        ("BFP SPRAY LINE (FEED WATER) TO DEAERATOR PRDS I/L MOV 10LAE10AA110", False, "", "AMP"),
        ("DISTRIBUTOR LINE TO FEEDWATER TRANSMITTER 10LAB30CP001", False, "", "JAPA"),
        ("INLET FEEDWATER PRESSURE TRANSMITTER 10HAC90CP001", False, "", "JAPA"),
        ("INLET FEEDWATER FLOW TRANSMITTER 10HAC90CF001", False, "", "JAPA"),
        ("INLET FEEDWATER FLOW TRANSMITTER 10HAC90CF002", False, "", "JAPA")
    ]),
    (27, "WO-100826-0038", "OM EIC Y1 UNIT 1 DESH SUPERHEATER LINE 1", "BOILER", "22/08/2026", "IN PROGRESS", "M TOHER", [
        ("CALIBRATION/FUNCTION TEST SPRAY CONTROL VALVE 10LAE10EX001", True, "22/08/2026", "M TOHER"),
        ("CALIBRATION/FUNCTION ISOLATION (ON/OFF) VALVE", True, "22/08/2026", "M TOHER"),
        ("DESH 1 SPRAY WATER FLOW TRANSMITTER 10LAE20CF001", False, "", "")
    ]),
    (28, "WO-100826-0039", "OM EIC Y1 UNIT 1 DESH SUPERHEATER LINE 2", "BOILER", "22/08/2026", "IN PROGRESS", "M TOHER", [
        ("DESH 2 SPRAY WATER FLOW TRANSMITTER 10LAE30CF001", True, "22/08/2026", "JAPA"),
        ("CALIBRATION/FUNCTION TEST SPRAY CONTROL VALVE 10LAE12EX001", True, "22/08/2026", "AMP"),
        ("BEFORE DESH 2 TEMP TRANSMITTER CALIBRATION (20HAH46CT001, 10HAH36CT009, 10HAH36CT009)", False, "", "MSW"),
        ("CALIBRATION/FUNCTION ISOLATION (ON/OFF) VALVE", False, "", "AMP")
    ]),
    (29, "WO-100826-0040", "OM EIC Y1 UNIT 1 GENERATOR CIRCUIT BREAKER", "ELECTRICAL", "22/08/2026", "IN PROGRESS", "M ZAINI", [
        ("INSPECTION MEKANIK PENGGERAK", True, "22/08/2026", "M ZAINI"),
        ("INSPECTION MOTOR CHARGING", True, "22/08/2026", "M ZAINI"),
        ("INSPECTION BEARING DRIVE RACK OUT/IN", True, "22/08/2026", "M ZAINI"),
        ("REGREASING SOCKET MAIN KONTAK", False, "", ""),
        ("INSPECTION SYSTEM KONTROL", False, "", ""),
        ("TEST TAHANAN KONTAK", False, "", ""),
        ("TEST KESEREMPAKAN", False, "", ""),
        ("INSPECTION TAHANAN ISOLASI KONTAK", False, "", ""),
        ("INSPECTION TAHANAN ISOLASI BUS BAR", False, "", ""),
        ("FUNCTION TEST", False, "", ""),
        ("PENGUKURAN TAHANAN MOTOR CHARGING, CLOSING DAN TRIPPING COIL", False, "", ""),
        ("INSPECTION MODUL CONTROL BREAKER", False, "", ""),
        ("INSPECTION LAMPU SWITCH GEAR GCB", False, "", ""),
        ("INDIKATOR DAN LAMPU PANEL SWITCH GEAR GCB", False, "", ""),
        ("PENGETESAN POWER DC UNTUK SUPPLY CONTROL 6,3 KV SWITCH GEAR GCB", False, "", ""),
        ("INSPECTION HEATER CUBICLE SWITCH GEAR GCB", False, "", ""),
        ("INSPECTION DAN CLEANING TERMINASI SWITCH GEAR GCB", False, "", ""),
        ("INSPECTION DAN PENGUJIAN RELAY PROTEKSI SWITCH GEAR GCB", False, "", ""),
        ("INSPECTION GROUNDING SYSTEM SWITCH GEAR GCB", False, "", ""),
        ("INSPECTION TAHANAN ISOLASI BUS BAR SWITCH GEAR GCB", False, "", ""),
        ("INSPECTION CT & PT SWITCH GEAR GCB", False, "", ""),
        ("FUNCTION TEST SWITCH GEAR GCB", False, "", ""),
        ("INSPECTION HEATER SYSTEM", False, "", ""),
        ("INSPECTION DISPLAY BREAKER", False, "", ""),
        ("INSPECTION HEATER BUSDUCT", False, "", ""),
        ("INSPECTION BOLT BUSBAR, FLANGE & INSPECTION HOLE BUSDUCT", False, "", ""),
        ("INSPECTION SILICA BUSDUCT", False, "", ""),
        ("CEK KEBOCORAN DAN KELEMBAPAN BUSDUCT", False, "", ""),
        ("INSPECTION CONTACT RESISTANCE BUSDUCT", False, "", ""),
        ("INSPECTION ISOLATION RESISTANCE BUSDUCT", False, "", "")
    ]),
    (30, "WO-100826-0041", "OM EIC Y1 UNIT 1 GENERATOR", "ELECTRICAL", "22/08/2026", "SCHED-OK", "M ZAINI", [
        ("DISASSEMBLY BRACKET GENERATOR SISI FRONT", False, "", "JAPA"),
        ("DISASSEMBLY BRACKET GENERATOR SISI REAR", False, "", "JAPA"),
        ("DISASSEMBLY OIL DEFLECTOR BEARING", False, "", "JAPA"),
        ("CLEANING BODY GENERATOR", False, "", "JAPA"),
        ("CLEANING OIL DEFLECTOR BEARING", False, "", "JAPA"),
        ("CLEANING BOLT & NUT", False, "", "JAPA"),
        ("INSPECTION OIL DEFLECTOR BEARING 3 & 4", False, "", "JAPA"),
        ("INSPECTION SHROUD & FAN BLADE", False, "", "JAPA"),
        ("INSPECTION STATOR GENERATOR (IR, PI)", False, "", "JAPA"),
        ("INSPECTION ROTOR GENERATOR (IR, PI, RSO)", False, "", "JAPA"),
        ("INSPECTION VISUAL ISOLATOR", False, "", "JAPA"),
        ("INSPECTION ROTOR GROUNDING", False, "", "JAPA"),
        ("INSPECTION VISUAL FLEXIBLE ISOLATOR", False, "", "JAPA"),
        ("INSPECTION BRUSH GROUNDING", False, "", "JAPA"),
        ("INSPECTION TAHANAN ISOLASI GENERATOR", False, "", "JAPA"),
        ("INSPECTION HEATER NEUTRAL SIDE CUBICLE", False, "", "JAPA"),
        ("INSPECTION HEATER LINE SIDE CUBICLE", False, "", "JAPA"),
        ("ASSEMBLY OIL DEFLECTOR BEARING", False, "", "JAPA"),
        ("ASSEMBLY BRACKET SISI FRONT", False, "", "JAPA"),
        ("ASSEMBLY BRACKET SISI REAR", False, "", "JAPA"),
        ("PENGUKURAN TAHANAN RESISTOR", False, "", "JAPA"),
        ("INSPECTION & CLEANING PT", False, "", "JAPA"),
        ("INSPECTION & CLEANING CT", False, "", "JAPA"),
        ("PENGUKURAN TAHANAN ISOLASI PERMANEN MAGNET GENERATOR (PMG)", False, "", "JAPA"),
        ("INSPECTION DIODA EXCITER PERMANEN MAGNET GENERATOR (PMG)", False, "", "JAPA"),
        ("INSPECTION TERMINASI PERMANEN MAGNET GENERATOR (PMG)", False, "", "JAPA"),
        ("INSPECTION GROUNDING SYSTEM PERMANEN MAGNET GENERATOR (PMG)", False, "", "JAPA"),
        ("INSPECTION FUSE PANEL PERMANEN MAGNET GENERATOR (PMG)", False, "", "JAPA"),
        ("INSPECTION DISCONNECTING SWITCH NETRAL GROUNDING RESISTANCE (NGR)", False, "", "JAPA"),
        ("INSPECTION TRAFO NETRAL GROUNDING RESISTANCE (NGR)", False, "", "JAPA"),
        ("INSPECTION ISOLATOR BUSHING NETRAL GROUNDING RESISTANCE (NGR)", False, "", "JAPA"),
        ("INSPECTION TERMINASI NETRAL GROUNDING RESISTANCE (NGR)", False, "", "JAPA"),
        ("TEST TAHANAN ISOLASI NETRAL GROUNDING RESISTANCE (NGR)", False, "", "JAPA"),
        ("INSPECTION HEATER BUSDUCT NETRAL GROUNDING RESISTANCE (NGR)", False, "", "JAPA"),
        ("INSPECTION BOLT BUSBAR, FLANGE & INSPECTION HOLE BUSDUCT", False, "", "JAPA"),
        ("INSPECTION SILICA BUSDUCT", False, "", "JAPA"),
        ("CEK KEBOCORAN DAN KELEMBAPAN BUSDUCT", False, "", "JAPA"),
        ("INSPECTION CONTACT RESISTANCE BUSDUCT", False, "", "JAPA"),
        ("INSPECTION ISOLATION RESISTANCE BUSDUCT", False, "", "JAPA"),
        ("CLEANING", False, "", "JAPA")
    ]),
    (31, "WO-100826-0042", "OM EIC Y1 UNIT 1 AUXILIARY TRANSFORMER 2", "ELECTRICAL", "22/08/2026", "SCHED-OK", "M ZAINI", [
        ("INSPECTION ISOLATOR BUSHING", False, "", "JAPA"),
        ("INSPECTION TERMINASI", False, "", "JAPA"),
        ("CLEANING BUSHING CONNECTION HV & LV", False, "", "JAPA"),
        ("INSPECTION DAN CLEANING PANEL", False, "", "JAPA"),
        ("INSPECTION SILICAGEL", False, "", "JAPA"),
        ("INSPECTION GROUNDING SYSTEM", False, "", "JAPA"),
        ("INSPECTION KEBOCORAN MINYAK TRAFO", False, "", "JAPA"),
        ("PROTECTIVE DEVICE TEST DAN RESET TRAFO", False, "", "JAPA"),
        ("INSPECTION PANEL TAP CHANGER", False, "", "JAPA"),
        ("INSPECTION TAHANAN ISOLASI WINDING TRAFO", False, "", "JAPA"),
        ("RDS TEST", False, "", "JAPA"),
        ("MECHANICAL RELAY TEST", False, "", "JAPA"),
        ("INSPECTION DISCONNECTING SWITCH NETRAL GROUNDING RESISTANCE (NGR)", False, "", "JAPA"),
        ("INSPECTION TRAFO NETRAL GROUNDING RESISTANCE (NGR)", False, "", "JAPA"),
        ("INSPECTION ISOLATOR BUSHING NETRAL GROUNDING RESISTANCE (NGR)", False, "", "JAPA"),
        ("INSPECTION TERMINASI NETRAL GROUNDING RESISTANCE (NGR)", False, "", "JAPA"),
        ("INSPECTION GROUNDING SYSTEM NETRAL GROUNDING RESISTANCE (NGR)", False, "", "JAPA"),
        ("INSPECTION HEATER BUSDUCT", False, "", "JAPA"),
        ("INSPECTION BOLT BUSBAR, FLANGE & INSPECTION HOLE BUSDUCT", False, "", "JAPA"),
        ("INSPECTION SILICA BUSDUCT", False, "", "JAPA"),
        ("CEK KEBOCORAN DAN KELEMBAPAN BUSDUCT", False, "", "JAPA"),
        ("INSPECTION CONTACT RESISTANCE BUSDUCT", False, "", "JAPA"),
        ("INSPECTION ISOLATION RESISTANCE BUSDUCT", False, "", "JAPA"),
        ("CLEANING", False, "", "JAPA")
    ]),
    (32, "WO-100826-0043", "OM EIC Y1 UNIT 1 6.6KV MEDIUM VOLTAGE STATION BOARDS PANEL", "ELECTRICAL", "22/08/2026", "IN PROGRESS", "M ZAINI", [
        ("MSW20BBA10GS101:UNIT 1 SWITCHGEAR 6.6KV INCOMING PANEL (MV UAT 2 CB9)", True, "22/08/2026", "JAPA"),
        ("MSW20BBA10GS102:UNIT 1 SWITCHGEAR 6,6KV UNIT 1 OUTGOING FEEDER 1 PA FAN 1", False, "", "JAPA"),
        ("MSW20BBA10GS103:UNIT 1 SWITCHGEAR 6,6KV UNIT 1 OUTGOING FEEDER 2 PA FAN 2", False, "", "JAPA"),
        ("MSW20BBA10GS104:UNIT 1 SWITCHGEAR 6,6KV UNIT 1 OUTGOING FEEDER 3 SA FAN 1", False, "", "JAPA"),
        ("MSW20BBA10GS105:UNIT 1 SWITCHGEAR 6,6KV UNIT 1 OUTGOING FEEDER 4 SA FAN 2", False, "", "JAPA"),
        ("MSW20BBA10GS106:UNIT 1 SWITCHGEAR 6,6KV UNIT 1 OUTGOING FEEDER 5 ID FAN 1", False, "", "JAPA"),
        ("MSW20BBA10GS107:UNIT 1 SWITCHGEAR 6,6KV UNIT 1 OUTGOING FEEDER 6 ID FAN 2", False, "", "JAPA"),
        ("MSW20BBA10GS108:UNIT 1 SWITCHGEAR 6,6KV UNIT 1 OUTGOING FEEDER 8 BF PUMP 1", False, "", "JAPA"),
        ("MSW20BBA10GS109:UNIT 1 SWITCHGEAR 6,6KV UNIT 1 OUTGOING FEEDER 9 BF PUMP 2", False, "", "JAPA"),
        ("MSW20BBA10GS110:UNIT 1 SWITCHGEAR 6,6KV UNIT 1 OUTGOING FEEDER 7 CW PUMP 3", False, "", "JAPA"),
        ("MSW20BBA10GS111:UNIT 1 SWITCHGEAR 6,6KV UNIT 1 OUTGOING FEEDER 11 CW PUMP 4", False, "", "JAPA"),
        ("MSW20BBA10GS112:UNIT 1 SWITCHGEAR 6,6KV UNIT 1 OUTGOING FEEDER 12 CW PUMP 5", False, "", "JAPA"),
        ("MSW20BBA10GS113:UNIT 1 SWITCHGEAR 6,6KV UNIT 1 TRAFO FEEDER", False, "", "JAPA"),
        ("UNIT 1 SWITCHGEAR 6,6KV UNIT 1 ADAPTER", False, "", "JAPA"),
        ("MSW20BBA10GS114:UNIT 1 SWITCHGEAR 6,6KV METERING (L10)", False, "", "JAPA")
    ]),
    (33, "WO-100826-0044", "OM EIC Y1 UNIT 1 MEDIUM VOLTAGE STATION BOARDS COMMON", "ELECTRICAL", "22/08/2026", "SCHED-OK", "H AIDI", [
        ("SWITCHGEAR 6,6KV UNIT 1 INCOMMING GENERATOR 1", False, "", "H AIDI"),
        ("SWITCHGEAR 6,6KV UNIT 1 INCOMMING GENERATOR 2", False, "", "H AIDI"),
        ("SWITCHGEAR 6,6KV UNIT 1 INCOMMING GENERATOR 3", False, "", "H AIDI"),
        ("SWITCHGEAR 6,6KV UNIT 1 INCOMMING GENERATOR 4", False, "", "H AIDI"),
        ("SWITCHGEAR 6,6KV UNIT 1 OUTGOING TRAFO 1", False, "", "H AIDI"),
        ("SWITCHGEAR 6,6KV UNIT 1 OUTGOING TRAFO 2", False, "", "H AIDI"),
        ("MSW00BBA10CE201:MV COMMON METERING", False, "", "H AIDI"),
        ("MSW00BBA10GH201:SWITCHGEAR 6.6KV COMMON BUSTIE RIGHT", False, "", "H AIDI"),
        ("MSW00BBA10GH202:SWITCHGEAR 6.6KV COMMON BUSTIE LEFT", False, "", "H AIDI"),
        ("MSW00BBA10GH203:SWITCHGEAR 6.6KV COMMON TRAFO FEEDER", False, "", "H AIDI")
    ]),
    (34, "WO-100826-0045", "OM EIC Y1 UNIT 1 MAIN TURBINE", "TURBINE", "22/08/2026", "SCHED-OK", "M TOHER", [
        ("CONDENSATE PRESSURE TO BYPASS SPRAY PRESSURE TRANSMITTER (20LCE40CP001)", False, "", "M TOHER"),
        ("CONDENSATE PRESSURE TO BYPASS SPRAY PRESSURE TRANSMITTER (20LCE40CP002)", False, "", "M TOHER"),
        ("CONDENSATE PRESSURE TO BYPASS SPRAY PRESSURE TRANSMITTER (20LCE40CP003)", False, "", "M TOHER"),
        ("ACTUATOR TURBINE EXTRACTION III TO DEAERATOR CV 10LBD20AA210", False, "", "M TOHER"),
        ("ACTUATOR MOV TURBINE STOP VALVE UNIT 1", False, "", "M TOHER"),
        ("ACTUATOR MOV PREHEATING 1 TURBINE", False, "", "M TOHER"),
        ("ACTUATOR MOV PREHEATING 2 TURBINE", False, "", "M TOHER"),
        ("TURBINE EXTRACTION II TO LPH2 TEMPERATURE TRANSMITTER (20LBD30CT001)", False, "", "M TOHER"),
        ("TURBINE EXTRACTION III TO DEAERATOR TEMPERATURE TRANSMITTER (20LBD20CT001)", False, "", "M TOHER"),
        ("TURBINE EXTRACTION I TO LPH1 TEMPERATURE TRANSMITTER (20LBD10CT001)", False, "", "M TOHER"),
        ("MSW20MAA10CP302 : UNIT 1 TURBINE BEHIND CONTROL STAGE PRESSURE TRANSMITTER (20MAA10CP001)", False, "", "M TOHER"),
        ("MSW20MAA10CP303 : UNIT 1 TURBINE EXHAUST PRESSURE TRANSMITTER (20MAA10CP002)", False, "", "M TOHER"),
        ("MSW20MAA10CP304 : UNIT 1 TURBINE EXHAUST PRESSURE TRANSMITTER (20MAA10CP003)", False, "", "M TOHER"),
        ("MSW20MAA10CP305 : UNIT 1 TURBINE EXHAUST PRESSURE TRANSMITTER (20MAA10CP004)", False, "", "M TOHER"),
        ("MSW20MAA10CP306 : UNIT 1 TURBINE BEHIND CONTROL STAGE PRESSURE TRANSMITTER (20MAA10CP005)", False, "", "M TOHER"),
        ("MOV TURBINE STEAM EXTRACTION-1", False, "", "M TOHER"),
        ("MOV TURBINE STEAM EXTRACTION-2", False, "", "M TOHER"),
        ("MOV MAIN STEAM DRAIN STG-2", False, "", "M TOHER"),
        ("TURBINE CASING TEMPERATURE - INSIDE TRANSMITTER 10MAA10CT012", False, "", "M TOHER"),
        ("TURBINE CASING TEMPERATURE - CENTER TRANSMITTER 10MAA10CT013", False, "", "M TOHER"),
        ("DEAERATOR PRDS OUTLET TO EXTRACTION I - DEAERATOR I/L TEMP TRANSMITTER 10LBD11CT002", False, "", "M TOHER"),
        ("DEAERATOR PRDS OUTLET TO EXTRACTION I - DEAERATOR I/L TEMP TRANSMITTER 10LBD11CT001", False, "", "M TOHER"),
        ("DEAERATOR PRDS TO OUTLET EXTRACTION TRANSMITTER 10LBD11CP001", False, "", "M TOHER"),
        ("DEAERATOR PRDS TO OUTLET EXTRACTION II TRANSMITTER 10LBD11CP002", False, "", "M TOHER"),
        ("FEEDWATER STORAGE TANK PRESSURE TRANSMITTER 10LAA20CP001", False, "", "M TOHER"),
        ("CONTROL VALVE LPH-1", False, "", "M TOHER"),
        ("CONTROL VALVE LPH-2", False, "", "M TOHER"),
        ("LP HEATER 2 TRANSMITTER 10LCC40CL001", False, "", "M TOHER"),
        ("LP HEATER 2 TRANSMITTER 10LCC40CL002", False, "", "M TOHER"),
        ("LPH II - TUBE SIDE OUTLET TO DEAERATOR TEMP TRANSMITTER 10LCC20CT001", False, "", "M TOHER"),
        ("FEEDWATER STORAGE TANK TRANSMITTER 10LAA20CT001", False, "", "M TOHER"),
        ("CYCLE MAKE UP PUMP DEAERATOR TRANSMITTER 10HGC20CF001", False, "", "M TOHER"),
        ("DEAERATOR TANK LEVEL 1 TRANSMITTER 10LAA20CL001", False, "", "M TOHER"),
        ("DEAERATOR TANK LEVEL 2 TRANSMITTER 10LAA20CL002", False, "", "M TOHER"),
        ("DEAERATOR TANK LEVEL 3 TRANSMITTER 10LAA20CL003", False, "", "M TOHER"),
        ("TURBINE EXTRACTION III TO DEAERATOR PRESSURE TRANSMITTER 10LBD20CP001", False, "", "M TOHER"),
        ("TURBINE EXTRACTION III TO LPH PRESSURE TRANSMITTER 10LBD30CP001", False, "", "M TOHER"),
        ("TURBINE EXTRACTION 1 TO PNEUMATIC OPERATED VALVE PRESSURE TRANSMITTER 10LBS10CP001", False, "", "M TOHER"),
        ("LP HEATER 1 TRANSMITTER 10LCC30CL001", False, "", "M TOHER"),
        ("LP HEATER 1 TRANSMITTER 10LCC30CL002", False, "", "M TOHER"),
        ("FLOW CONDESATE TO LP HEATER 1 TRANSMITTER 10LCA40CF001", False, "", "M TOHER"),
        ("CONDENSATE TO LP HEATER TRANSMITTER 10LCA40CF001", False, "", "M TOHER")
    ]),
    (35, "WO-100826-0046", "OM EIC 1Y FIRE ALARM LOCAL PANEL ( UNIT 1 )", "FIRE PROTECTION", "22/08/2026", "SCHED-OK", "JHON", [
        ("MSW00CYE10GH101 : ALARM SYSTEM ADMIN BUILDING", False, "", "JHON"),
        ("MSW00CYE10GH102 : ALARM SYSTEM DG SHEET", False, "", "JHON"),
        ("MSW00CYE10GH103 : PANEL MAIN FIRE ALARM SYSTEM", False, "", "JHON"),
        ("MSW00CYE10GH104 : ALARM SYSTEM DM MCC ROOM", False, "", "JHON"),
        ("MSW00CYE10GH105 : ALARM SYSTEM CHP MCC", False, "", "JHON"),
        ("MSW00CYE10GH106 : ALARM SYSTEM AHP MCC", False, "", "JHON"),
        ("MSW00CYE10GH107 : ALARM SYSTEM COOLING WATER", False, "", "JHON"),
        ("MSW00CYE10GH108 : ALARM SYSTEM DM/RW.FW TW PUMP", False, "", "JHON"),
        ("MSW00CYE10GH109 : ALARM SYSTEM WORKSHOP OFFICE ROOM", False, "", "JHON"),
        ("MSW00CYE10GH110 : ALARM SYSTEM SWAS ROOM", False, "", "JHON"),
        ("MSW00CYE10GH111 : ALARM SYSTEM STG BUILDING", False, "", "JHON"),
        ("MSW00CYE10GH113 : ALARM SYSTEM SWITCHYARD BUILDING", False, "", "JHON"),
        ("MSW00CYE10GH114 : ALARM SYSTEM REMOTE SUBSTATION BUILDING", False, "", "JHON")
    ]),
    (36, "WO-100826-0047", "OM EIC 1Y UNIT 1 PRIMARY AIR FAN LINE", "BOILER", "22/08/2026", "IN PROGRESS", "FERRYUS", [
        ("INSPECTION AND CALIBRATION OXYGEN ANALYZER", True, "22/08/2026", "FERRYUS"),
        ("P.A APH OUTLET FLOW DP TRANSMITTER 10HLA15CF001", True, "22/08/2026", "FERRYUS"),
        ("P.A APH OUTLET FLOW DP TRANSMITTER 10HLA15CF002", True, "22/08/2026", "FERRYUS"),
        ("P.A APH OUTLET PRESSURE TRANSMITTER 10HLA15CP001", False, "", "FERRYUS")
    ]),
    (37, "WO-100826-0048", "OM EIC 1Y UNIT 1 SECONDARY AIR FAN LINE", "BOILER", "22/08/2026", "IN PROGRESS", "FERRYUS", [
        ("AIR SUB1 FLOW DP TRANSMITTER 10HJL10CF010", True, "22/08/2026", "FERRYUS"),
        ("AIR SUB2 FLOW DP TRANSMITTER 10HJL11CF010", True, "22/08/2026", "FERRYUS"),
        ("SA APH OUTLET FLOW TRANSMITTER 10HLA25CF001", True, "22/08/2026", "FERRYUS"),
        ("SA APH OUTLET FLOW TRANSMITTER 10HLA25CF002", True, "22/08/2026", "FERRYUS"),
        ("SA APH OUTLET PRESSURE TRANSMITTER 10HLA25CP001", True, "22/08/2026", "FERRYUS"),
        ("UNIT 1 SECONDARY AIR FAN IGV SUB 1 20HJL10AA010", False, "", "FERRYUS"),
        ("UNIT 1 SECONDARY AIR FAN IGV SUB 2 20HJL11AA010", False, "", "FERRYUS"),
        ("UNIT 1 SECONDARY AIR FAN IGV SA CONTROL DAMPER 20HLA25AA010", False, "", "FERRYUS")
    ]),
    (38, "WO-100826-0049", "OM EIC Y1 UNIT 1 BOILER DISTRIBUTED CONTROL PANEL", "DCS", "22/08/2026", "SCHED-OK", "JHON", [
        ("PM PC OWS", False, "", "JHON"),
        ("PM PC EWS", False, "", "JHON"),
        ("PM panel RIO", False, "", "JHON")
    ]),
    (39, "WO-100826-0050", "OM EIC Y1 UNIT 1 BOILER DRUM", "BOILER", "22/08/2026", "IN PROGRESS", "JHON", [
        ("INSPECTION & CALIBRATION STEAM DRUM VENTING ISOLATION VALVE", True, "22/08/2026", "JHON"),
        ("INSPECTION & CALIBRATION STEAM DRUM MOV VENTING REGULATING VALVE", True, "22/08/2026", "JHON"),
        ("INSPECTION & CALIBRATION STEAM DRUM CBD ISOLATION VALVE", True, "22/08/2026", "JHON"),
        ("INSPECTION & CALIBRATION STEAM DRUM MOV CBD REGULATING VALVE", True, "22/08/2026", "JHON"),
        ("INSPECTION & CALIBRATION STEAM DRUM IBD ISOLATION VALVE", True, "22/08/2026", "JHON"),
        ("INSPECTION & CALIBRATION STEAM DRUM MOV IBD REGULATING VALVE", True, "22/08/2026", "JHON"),
        ("DRUM LEVEL TRANSMITTER 10HAD10CL001", False, "", "JHON"),
        ("DRUM LEVEL TRANSMITTER 10HAD10CL002", False, "", "JHON"),
        ("DRUM LEVEL TRANSMITTER 10HAD10CL003", False, "", "JHON"),
        ("DRUM PRESSURE TRANSMITTER 10HAD10CP002", False, "", "JHON"),
        ("DRUM PRESSURE TRANSMITTER 10HAD10CP003", False, "", "JHON"),
        ("DRUM PRESSURE TRANSMITTER 10HAD10CP001", False, "", "JHON")
    ]),
    (40, "WO-100826-0051", "OM EIC Y1 UNIT 1 COMBUSTOR", "BOILER", "22/08/2026", "IN PROGRESS", "M TOHER", [
        ("COMBUSTER ASH DRAIN 1 (BED ASH COOLER DRAIN) MOV 10HHC01AA001", True, "22/08/2026", "M TOHER"),
        ("COMBUSTER ASH DRAIN 2 (EMERGENCY ASH DRAIN) MOV 10HHC01AA002", True, "22/08/2026", "M TOHER"),
        ("LIMESTONE GATE VALVE", True, "22/08/2026", "M TOHER"),
        ("ACTUATOR BED MATERIAL DISCHARGE GATE VALVE 10ETG31AA01", True, "22/08/2026", "M TOHER"),
        ("COMBUSTOR LOWER PRESSURE TRANSMITTER 10HHC01CP001", True, "22/08/2026", "M TOHER"),
        ("MSW20HHC10CP102 : UNIT 1 COMBUSTOR DP WITH GRATE 10HHC01CP011", False, "", ""),
        ("MSW20HHC10CP103 : UNIT 1 COMBUSTOR UPPER DP 10HHC01CP012", False, "", ""),
        ("AIR COMBUSTOR AT LEVEL PRES TRANSMITTER 10HHC01CP060", False, "", ""),
        ("MSW20HHC10CT101 : UNIT 1 COMBUSTOR LOWER TEMP 10HHC01CT011", False, "", ""),
        ("MSW20HHC10CT102 : UNIT 1 COMBUSTOR LOWER TEMP 10HHC01CT012", False, "", ""),
        ("MSW20HHC10CT103 : UNIT 1 COMBUSTOR LOWER TEMP 10HHC01CT013", False, "", ""),
        ("MSW20HHC10CT104 : UNIT 1 COMBUSTOR MIDDLE TEMP 10HHC01CT041", False, "", ""),
        ("MSW20HHC10CT105 : UNIT 1 COMBUSTOR MIDDLE TEMP 10HHC01CT042", False, "", ""),
        ("MSW20HHC10CT106 : UNIT 1 COMBUSTOR MIDDLE TEMP 10HHC01CT043", False, "", ""),
        ("INLET BACKPASS PRESSURE TRANSMITTER 10HBK01CP003", False, "", ""),
        ("INLET BACKPASS PRESSURE TRANSMITTER 10HBK01CP002", False, "", ""),
        ("INLET BACKPASS PRESSURE TRANSMITTER 10HBK01CP001", False, "", ""),
        ("BACKPASS PRESSURE AFTER LT SH TRANSMITTER 10HBK01CP030", False, "", ""),
        ("BACKPASS PRESSURE AFTER ECO TRANSMITTER 10HBK01CP050", False, "", "")
    ]),
    (41, "WO-100826-0052", "OM EIC Y1 UNIT 1 CYCLONE", "BOILER", "22/08/2026", "IN PROGRESS", "M TOHER", [
        ("MSW20HDF10CP102 : UNIT 1 BACKPASS INLET PRESSURE", True, "22/08/2026", "M TOHER"),
        ("CYCLONE TO SEALPOT PRESSURE TRANSMITTER 10HDF01CP001", False, "", "M TOHER"),
        ("MSW20HDF10CT101 : UNIT 1 BACKPASS INLET TEMPERATURE", False, "", "M TOHER"),
        ("MSW20HDF10CT102 : UNIT 1 CYCLONE OUTLET TEMP 10HNA01CT001", False, "", "M TOHER"),
        ("MSW20HDF10CT103 : UNIT 1 BACKPASS INLET TEMPERATURE", False, "", "M TOHER"),
        ("MSW20HDF10CT104 : UNIT 1 CYCLONE INLET TEMPERATURE", False, "", "M TOHER")
    ]),
    (42, "WO-100826-0053", "OM EIC Y1 UNIT 1 SEALPOT", "BOILER", "22/08/2026", "SCHED-OK", "M ZAINI", [
        ("ACTUATOR DAMPER SEALPOT BLOWER 1", False, "", "M ZAINI"),
        ("ACTUATOR DAMPER SEALPOT BLOWER 2", False, "", "M ZAINI"),
        ("CALIBRATION PRESSURE TRANSMITTER", False, "", "M ZAINI"),
        ("CALIBRATION TEMPERATURE TRANSMITTER", False, "", "M ZAINI")
    ]),
    (43, "WO-100826-0054", "OM EIC Y1 UNIT 1 SUPERHEATER SYSTEM LINE", "BOILER", "22/08/2026", "IN PROGRESS", "M ZAINI", [
        ("ERV PRESSURE SWITCH 10LBA20CP502", True, "22/08/2026", "M ZAINI"),
        ("INSPECTION AND CALIBRATION TEMP TRANSMITTER 10LBA10CT001", True, "22/08/2026", "M ZAINI"),
        ("INSPECTION AND CALIBRATION TEMP TRANSMITTER 10LBA10CT002", False, "", "M ZAINI"),
        ("INSPECTION AND CALIBRATION TEMP TRANSMITTER 10LBA10CT003", False, "", "M ZAINI"),
        ("ACTUATOR MAIN STEAM LINE (START UP BYPASS) TO DEAERATOR PRDS I/L CV 10LBH10AA210", False, "", "M ZAINI"),
        ("MS START-UP VENT VALVE (REGULATING) MOV 10LBA21AA011", False, "", "M ZAINI"),
        ("MS START-UP VENT VALVE (ISOLATION) MOV 10LBA21AA001", False, "", "M ZAINI"),
        ("MAIN STEAM LIVE PRESSURE TRANSMITTER 10LAB10CP001", False, "", "M ZAINI"),
        ("MAIN STEAM LIVE PRESSURE TRANSMITTER 10LAB10CP002", False, "", "M ZAINI"),
        ("MAIN STEAM LIVE PRESSURE TRANSMITTER 10LAB10CP003", False, "", "M ZAINI"),
        ("INSPECTION AND CALIBRATION FLOW TRANSMITTER 10LBA10CF001", False, "", "M ZAINI"),
        ("INSPECTION AND CALIBRATION FLOW TRANSMITTER 10LBA10CF002", False, "", "M ZAINI")
    ]),
    (44, "WO-100826-0055", "OM EIC Y1 UNIT 1 JACKING OIL PUMP", "TURBINE", "22/08/2026", "SCHED-OK", "M TOHER", [
        ("MSW20MAV10-M101 : UNIT 1 JACKING OIL PUMP MOTOR", False, "", "MSW"),
        ("MSW20MAV10CP101 : UNIT 1 JACKING OIL PRESSURE TRANSMITTER", False, "", "MSW")
    ]),
    (45, "WO-100826-0056", "OM EIC Y1 UNIT 1 MAIN OIL PUMP", "TURBINE", "22/08/2026", "SCHED-OK", "H AIDI", [
        ("INSPEKSI & PM OIL PUMP MOTOR ( AUXILIARY, EMERGENCY, JACKING, BREATHER )", False, "", "MSW"),
        ("INSPEKSI DAN KALIBRASI LUB OIL PRESSURE TRANSMITTER 10MAV40CP001", False, "", "JAPA"),
        ("INSPEKSI DAN KALIBRASI LUB OIL PRESSURE TRANSMITTER 10MAV40CP002", False, "", "JAPA"),
        ("INSPEKSI DAN KALIBRASI LUB OIL PRESSURE TRANSMITTER 10MAV40CP003", False, "", "JAPA")
    ]),
    (46, "WO-100826-0057", "OM EIC Y1 UNIT 1 TURBINE CONTROL VALVE", "TURBINE", "22/08/2026", "SCHED-OK", "H AIDI", [
        ("VALVE POSITION BLOCK LIVE STEAM PT (20MAX45CP001)", False, "", "JAPA"),
        ("VALVE POSITION BLOCK LIVE STEAM PT (20MAX45CP002)", False, "", "JAPA"),
        ("VALVE POSITION BLOCK LIVE STEAM PT (20MAX45CP003)", False, "", "JAPA"),
        ("VALVE BLOCK - OUTLET POSITION LIVE STEAM PT (20MAX45CP004)", False, "", "JAPA"),
        ("CONTROL OIL PRESSURE PT (20MAX40CP001)", False, "", "JAPA"),
        ("VALVE CHEST TEMPERATURE TRANSMITTER 10MAA10CT011", False, "", "MSW"),
        ("LIVE STEAM PRESSURE TRANSMITTER 10LBA10CP001", False, "", "JAPA"),
        ("CALIBRATION/FUNCTION TEST CONTROL VALVE", False, "", "MSW")
    ]),
    (47, "WO-100826-0058", "OM EIC Y1 UNIT 1 HP BYPASS VALVE", "TURBINE", "22/08/2026", "SCHED-OK", "JHON", [
        ("CALIBRATION/FUNCTION TEST HP BYPASS CONTROL VALVE 20LBF10AA210", False, "", "AMP"),
        ("HP BYPASS TEMPERATURE TRANSMITTER 10LBF10CT001", False, "", "MSW"),
        ("BYPASS PRESSURE TRANSMITTER 10MAG10CP001", False, "", "JAPA"),
        ("MSW20LBF10CG101 : UNIT 1 STEAM BYPASS REDUCING CONTROL VALVE PRESSURE TRANSMITTER", False, "", "JAPA"),
        ("MSW20LBF10CP101 : UNIT 1 STEAM BYPASS REDUCING PRESSURE TRANSMITTER 10LBF10CP001", False, "", "JAPA"),
        ("MSW20LBF10CT101 : UNIT 1 STEAM BYPASS REDUCING TEMPERATURE TRANSMITTER", False, "", "MSW")
    ]),
    (48, "WO-100826-0059", "OM EIC Y1 UNIT 1 TURBINE DRAINAGE MAIN HEADER LINE TO EXPANSION TUBE", "TURBINE", "22/08/2026", "SCHED-OK", "M ZAINI", [
        ("DRAIN OF ESV 10MAL10AA210", False, "", "M ZAINI"),
        ("DRAIN OF CV CHAMBER 10MAL20AA210", False, "", "M ZAINI"),
        ("TURBINE DRAIN VALVE AFTER FIRST STAGE 10MAL30AA210", False, "", "M ZAINI"),
        ("TURBINE DRAIN VALVE 10MAL40AA210", False, "", "M ZAINI"),
        ("TURBINE DRAIN VALVE 10MAL50AA210", False, "", "M ZAINI"),
        ("TURBINE DRAIN VALVE 10MAL60AA210", False, "", "M ZAINI"),
        ("TURBINE DRAIN VALVE 10MAL70AA210", False, "", "M ZAINI")
    ]),
    (49, "WO-100826-0060", "OM EIC Y1 UNIT 1 VACUUM PUMP A", "TURBINE", "22/08/2026", "SCHED-OK", "M ZAINI", [
        ("MSW20MAJ10-M102 : UNIT 1 VACUUM PUMP A MOTOR (MEGGER, INSPEKSI TERMINAL BLOK, DAN SISTEM COOLING MOTOR)", False, "", "JAPA"),
        ("DISCHARGE, SUCTION & VENTING VALVE VACUUM PUMP-1", False, "", "MSW"),
        ("MSW20MAJ10AA101 : UNIT 1 AIR REMOVAL SYSTEM VACUUM BREAKER SOLENOID VALVE", False, "", "MSW"),
        ("MSW20MAJ10CG101 : UNIT 1 AIR REMOVAL SYSTEM POSITION TRANSMITTER", False, "", "M ZAINI")
    ]),
    (50, "WO-100826-0061", "OM EIC Y1 UNIT 1 VACUUM PUMP B", "TURBINE", "22/08/2026", "SCHED-OK", "M ZAINI", [
        ("MSW20MAJ10-M202 : UNIT 1 VACUUM PUMP B MOTOR (MEGGER, INSPEKSI TERMINAL BLOK, DAN SISTEM COOLING MOTOR)", False, "", "JAPA"),
        ("DISCHARGE, SUCTION & VENTING VALVE VACUUM PUMP-2", False, "", "MSW"),
        ("MSW20MAJ10AA201 : UNIT 1 AIR REMOVAL SYSTEM VACUUM BREAKER SOLENOID VALVE", False, "", "MSW"),
        ("MSW20MAJ10CG201 : UNIT 1 AIR REMOVAL SYSTEM POSITION TRANSMITTER", False, "", "M ZAINI")
    ]),
    (51, "WO-100826-0062", "OM EIC Y1 UNIT 1 CONDENSER", "TURBINE", "22/08/2026", "SCHED-OK", "M IQBAL", [
        ("MSW20MAG10CP103 : UNIT 1 CONDENSER BYPASS PRESSURE TRANSMITTER 10MAG10CP001", False, "", "JAPA"),
        ("COOLING WATER SUPPLY TEMPERATURE TRANSMITTER 10PAB11CT001", False, "", "JAPA"),
        ("COOLING WATER SUPPLY TEMPERATURE TRANSMITTER 10PAB12CT001", False, "", "JAPA"),
        ("COOLING WATER RETURN TEMPERATURE TRANSMITTER 10PAB21CT001", False, "", "JAPA"),
        ("COOLING WATER RETURN TEMPERATURE TRANSMITTER 10PAB22CT001", False, "", "JAPA")
    ]),
    (52, "WO-100826-0063", "OM EIC Y1 UNIT 1 MAIN CONDENSATE PUMP A", "TURBINE", "22/08/2026", "SCHED-OK", "M ZAINI", [
        ("INSPECTION FRAME MOTOR", False, "", "JAPA"),
        ("REGREASING (JIKA DILENGKAPI NIPPLE GREASE)", False, "", "JAPA"),
        ("INSPECTION TAHANAN ISOLASI", False, "", "JAPA"),
        ("INSPECTION COOLING FAN", False, "", "JAPA"),
        ("INSPECTION TAHANAN WINDING", False, "", "JAPA"),
        ("INSPECTION TERMINASI", False, "", "JAPA"),
        ("INSPECTION KONEKSI GROUNDING SYSTEM", False, "", "JAPA"),
        ("CALIBRATION LIMIT SWITCH", False, "", "JAPA"),
        ("PRESSURE TRANSMITTER CONDENSATE PUMP TO DELIVERY 10LCA30CP001", False, "", "JAPA"),
        ("ACTUATOR CONDENSATE PUMP RECIRCULATION CONTROL VALVE 10LCA31AA210", False, "", "MSW"),
        ("ACTUATOR MAIN CONDENSATE CONTROL VALVE 10LCA30AA240", False, "", "MSW"),
        ("CEP DISCHARGE ISOLATION VALVE", False, "", "MSW")
    ]),
    (53, "WO-100826-0064", "OM EIC Y1 UNIT 1 MAIN CONDENSATE PUMP B", "TURBINE", "22/08/2026", "SCHED-OK", "M ZAINI", [
        ("INSPECTION FRAME MOTOR", False, "", "JAPA"),
        ("REGREASING (JIKA DILENGKAPI NIPPLE GREASE)", False, "", "JAPA"),
        ("INSPECTION TAHANAN ISOLASI", False, "", "JAPA"),
        ("INSPECTION COOLING FAN", False, "", "JAPA"),
        ("INSPECTION TAHANAN WINDING", False, "", "JAPA"),
        ("INSPECTION TERMINASI", False, "", "JAPA"),
        ("INSPECTION KONEKSI GROUNDING SYSTEM", False, "", "JAPA"),
        ("CALIBRATION LIMIT SWITCH", False, "", "JAPA"),
        ("CEP DISCHARGE ISOLATION VALVE", False, "", "MSW")
    ]),
    (54, "WO-100826-0065", "OM EIC Y1 UNIT 1 GENERATOR CONTROL PANEL", "ELECTRICAL", "22/08/2026", "IN PROGRESS", "M ZAINI", [
        ("PENGUJIAN PROTEKSI FREQUENCY", True, "22/08/2026", "MSW"),
        ("PENGUJIAN PROTEKSI DIFFERENSIAL GENERATOR", True, "22/08/2026", "MSW"),
        ("PENGUJIAN PROTEKSI SHORT CIRCUIT", True, "22/08/2026", "MSW"),
        ("PENGUJIAN PROTEKSI OVERCURRENT", True, "22/08/2026", "MSW"),
        ("PENGUJIAN PROTEKSI OVERVOLTAGE", True, "22/08/2026", "MSW"),
        ("PENGUJIAN PROTEKSI ROTOR EARTH FAULT", True, "22/08/2026", "MSW"),
        ("PENGUJIAN PROTEKSI STATOR EARTH FAULT", True, "22/08/2026", "MSW"),
        ("PENGUJIAN PROTEKSI REVERSE POWER", False, "", "MSW"),
        ("PENGUJIAN PROTEKSI UNDER EXCITATION", False, "", "MSW"),
        ("PENGUJIAN PROTEKSI OVER EXCITATION", False, "", "MSW"),
        ("PENGUJIAN PROTEKSI NEGATIVE SEQUENCE", False, "", "MSW"),
        ("PENGUJIAN PROTEKSI OVERLOAD", False, "", "MSW"),
        ("CLEANING DAN TIGHTNING", False, "", "MSW")
    ]),
    (55, "WO-100826-0066", "OM EIC Y1 UNIT 1 GENERATOR EXCITATION PANEL", "ELECTRICAL", "22/08/2026", "FINISH", "M ZAINI", [
        ("PERAWATAN BAGIAN EXTERNAL ENCLOSURE PANEL", True, "22/08/2026", "MSW"),
        ("MEMBERSIHKAN FILTER PANEL", True, "22/08/2026", "MSW"),
        ("PEMELIHARAAN FAN CONVERTER UNITROL", True, "22/08/2026", "MSW"),
        ("MEMBERSIHKAN KOMPARTEMEN DALAM PANEL", True, "22/08/2026", "MSW"),
        ("HOUSEKEEPING", True, "22/08/2026", "MSW")
    ]),
    (56, "WO-100826-0067", "OM EIC Y1 UNIT 1 SOOT BLOWER", "BOILER", "22/08/2026", "IN PROGRESS", "YOGA", [
        ("CLEANING, INSPECTION, & REGREASING ALL SOOT BLOWER MOTOR 1", True, "22/08/2026", "JAPA"),
        ("CLEANING, INSPECTION, & REGREASING ALL SOOT BLOWER MOTOR 2", True, "22/08/2026", "JAPA"),
        ("CLEANING, INSPECTION, & REGREASING ALL SOOT BLOWER MOTOR 3", True, "22/08/2026", "JAPA"),
        ("CLEANING, INSPECTION, & REGREASING ALL SOOT BLOWER MOTOR 4", True, "22/08/2026", "JAPA"),
        ("CLEANING, INSPECTION, & REGREASING ALL SOOT BLOWER MOTOR 5", True, "22/08/2026", "JAPA"),
        ("CLEANING, INSPECTION, & REGREASING ALL SOOT BLOWER MOTOR 6", True, "22/08/2026", "JAPA"),
        ("CLEANING, INSPECTION, & REGREASING ALL SOOT BLOWER MOTOR 7", True, "22/08/2026", "JAPA"),
        ("CLEANING, INSPECTION, & REGREASING ALL SOOT BLOWER MOTOR 8", True, "22/08/2026", "JAPA"),
        ("CLEANING, INSPECTION, & REGREASING ALL SOOT BLOWER MOTOR 9", True, "22/08/2026", "JAPA"),
        ("CLEANING, INSPECTION, & REGREASING ALL SOOT BLOWER MOTOR 10", True, "22/08/2026", "JAPA"),
        ("CLEANING, INSPECTION, & REGREASING ALL SOOT BLOWER MOTOR 11", True, "22/08/2026", "JAPA"),
        ("SOOT BLOWER STEAM OUTLET TRANSMITTER 10HCB10CP001", True, "22/08/2026", "JAPA"),
        ("SOOT BLOWER STEAM FLOW TRANSMITTER 10HCB10CF001", False, "", "JAPA"),
        ("ACTUATOR VALVE DRAIN SOOT BLOWER 10HCB10AA201", False, "", "AMP"),
        ("SOOT BLOWER VALVE MOV 10HCB10AA001", False, "", "AMP"),
        ("ACTUATOR SOOT BLOWER CONTROL VALVE 10HCB10EX001", False, "", "MSW")
    ]),
    (57, "WO-100826-0068", "OM EIC Y1 UNIT 1 TURBINE CONTROL PANEL", "TURBINE", "22/08/2026", "SCHED-OK", "JHON", [
        ("PM PC OWS", False, "", "JHON"),
        ("PM PC EWS", False, "", "JHON"),
        ("PM panel RIO", False, "", "JHON")
    ]),
    (58, "WO-100826-0069", "OM EIC Y1 UNIT 1 LV DISTRIBUTION", "ELECTRICAL", "22/08/2026", "SCHED-OK", "M IQBAL", [
        ("INSPEKSI LV TRANSFORMER", False, "", "JAPA"),
        ("RDC Test LV TRANSFORMER", False, "", "JAPA"),
        ("FUNGSI RACK OUT RACK IN", False, "", "JAPA"),
        ("PERAWATAN BAGIAN EXTERNAL ENCLOSURE MCC", False, "", "JAPA"),
        ("PERAWATAN KOMPARTEMEN BUSBAR", False, "", "JAPA"),
        ("PENGUJIAN TAHANAN ISOLASI BUSBAR *)sudah termasuk busbar dan busduct", False, "", "JAPA"),
        ("PENGUJIAN TAHANAN KONTAK BUSBAR", False, "", "JAPA"),
        ("PERAWATAN KOMPARTEMEN KABEL", False, "", "JAPA"),
        ("PERAWATAN KOMPARTEMEN MARSHALLING PANEL", False, "", "JAPA"),
        ("PERAWATAN KOMPARTEMEN TRAFO KONTROL", False, "", "JAPA"),
        ("PERAWATAN KOMPARTEMEN SOOTBLOWER MCC FEEDER", False, "", "JAPA"),
        ("PERAWATAN KOMPARTEMEN TG MCC FEEDER", False, "", "JAPA"),
        ("PERAWATAN KOMPARTEMEN ADAPTER PANEL", False, "", "JAPA"),
        ("PENGUJIAN TAHANAN KONTAK BUSDUCT BUSTIE", False, "", "JAPA"),
        ("PERAWATAN ACB INCOMMING", False, "", "JAPA"),
        ("PENGUJIAN TAHANAN ISOLASI ACB INCOMMING", False, "", "JAPA"),
        ("PENGUJIAN TAHANAN KONTAK ACB INCOMMING", False, "", "JAPA"),
        ("PENGUJIAN ANALISA CB", False, "", "JAPA"),
        ("PERAWATAN ACB ESP FEEDER", False, "", "JAPA"),
        ("PENGUJIAN TAHANAN ISOLASI ACB ESP FEEDER", False, "", "JAPA"),
        ("PENGUJIAN TAHANAN KONTAK ACB ESP FEEDER", False, "", "JAPA"),
        ("PENGUJIAN ANALISA CB ESP FEEDER", False, "", "JAPA"),
        ("PERAWATAN ACB BOILER FEEDER", False, "", "JAPA"),
        ("PENGUJIAN TAHANAN KONTAK ACB BOILER FEEDER", False, "", "JAPA"),
        ("PENGUJIAN ANALISA CB BOILER FEEDER", False, "", "JAPA"),
        ("PERAWATAN ACB COOLING TOWER MCC FEEDER", False, "", "JAPA"),
        ("PENGUJIAN TAHANAN ISOLASI ACB COOLING TOWER FEEDER", False, "", "JAPA"),
        ("PENGUJIAN TAHANAN KONTAK ACB COOLING TOWER FEEDER", False, "", "JAPA"),
        ("PENGUJIAN ANALISA CB COOLING TOWER FEEDER", False, "", "JAPA"),
        ("INSPECTION HEATER BUSDUCT", False, "", "JAPA"),
        ("INSPECTION BOLT BUSBAR, FLANGE & INSPECTION HOLE BUSDUCT", False, "", "JAPA"),
        ("INSPECTION SILICA BUSDUCT", False, "", "JAPA"),
        ("CEK KEBOCORAN DAN KELEMBAPAN BUSDUCT", False, "", "JAPA"),
        ("INSPECTION CONTACT RESISTANCE BUSDUCT", False, "", "JAPA"),
        ("INSPECTION ISOLATION RESISTANCE BUSDUCT", False, "", "JAPA"),
        ("HOUSEKEEPING", False, "", "JAPA")
    ]),
    (59, "WO-100826-0070", "OM EIC Y1 UNIT 1 380V MCC SWICTHGEAR BOILER", "ELECTRICAL", "22/08/2026", "SCHED-OK", "YOGA", [
        ("PERAWATAN BAGIAN EXTERNAL ENCLOSURE MCC", False, "", "JAPA"),
        ("PERAWATAN KOMPARTEMEN BUSBAR", False, "", "JAPA"),
        ("PENGUJIAN TAHANAN ISOLASI BUSBAR", False, "", "JAPA"),
        ("PENGUJIAN TAHANAN KONTAK BUSBAR", False, "", "JAPA"),
        ("PERAWATAN KOMPARTEMEN KABEL", False, "", "JAPA"),
        ("PERAWATAN KOMPARTEMEN MARSHALLING PANEL", False, "", "JAPA"),
        ("PERAWATAN MODULE WITHDRAWABLE", False, "", "JAPA"),
        ("PERAWATAN ACB INCOMMING", False, "", "JAPA"),
        ("PENGUJIAN TAHANAN ISOLASI ACB INCOMING", False, "", "JAPA"),
        ("PENGUJIAN TAHANAN KONTAK ACB", False, "", "JAPA"),
        ("PENGUJIAN ANALISA CB", False, "", "JAPA"),
        ("HOUSEKEEPING", False, "", "JAPA")
    ]),
    (60, "WO-100826-0071", "OM EIC Y1 UNIT 1 380V MCC SWICTHGEAR TG", "ELECTRICAL", "22/08/2026", "SCHED-OK", "M IQBAL", [
        ("PERAWATAN BAGIAN EXTERNAL ENCLOSURE MCC", False, "", "JAPA"),
        ("PERAWATAN KOMPARTEMEN BUSBAR", False, "", "JAPA"),
        ("PENGUJIAN TAHANAN ISOLASI BUSBAR", False, "", "JAPA"),
        ("PENGUJIAN TAHANAN KONTAK BUSBAR", False, "", "JAPA"),
        ("PERAWATAN KOMPARTEMEN KABEL", False, "", "JAPA"),
        ("PERAWATAN KOMPARTEMEN MARSHALLING PANEL", False, "", "JAPA"),
        ("PERAWATAN MODULE WITHDRAWABLE", False, "", "JAPA"),
        ("HOUSEKEEPING", False, "", "JAPA")
    ]),
    (61, "WO-100826-0072", "OM EIC Y1 UNIT 1 380V MCC SWICTHGEAR ESP", "ELECTRICAL", "22/08/2026", "IN PROGRESS", "M IQBAL", [
        ("PERAWATAN BAGIAN EXTERNAL ENCLOSURE MCC", True, "22/08/2026", "JAPA"),
        ("PERAWATAN KOMPARTEMEN BUSBAR", True, "22/08/2026", "JAPA"),
        ("PENGUJIAN TAHANAN ISOLASI BUSBAR", True, "22/08/2026", "JAPA"),
        ("PENGUJIAN TAHANAN KONTAK BUSBAR", True, "22/08/2026", "JAPA"),
        ("PERAWATAN KOMPARTEMEN KABEL", True, "22/08/2026", "JAPA"),
        ("PERAWATAN KOMPARTEMEN MARSHALLING PANEL", True, "22/08/2026", "JAPA"),
        ("PERAWATAN MODULE WITHDRAWABLE", True, "22/08/2026", "JAPA"),
        ("PERAWATAN ACB INCOMMING", True, "22/08/2026", "JAPA"),
        ("PENGUJIAN TAHANAN ISOLASI ACB INCOMMING", True, "22/08/2026", "JAPA"),
        ("PENGUJIAN TAHANAN KONTAK ACB INCOMMING", True, "22/08/2026", "JAPA"),
        ("PENGUJIAN ANALISA CB", True, "22/08/2026", "JAPA"),
        ("HOUSEKEEPING", False, "", "JAPA")
    ]),
    (62, "WO-100826-0073", "OM Y1 EIC UNIT 1 GLAND STEAM SEALING CONDENSER", "TURBINE", "22/08/2026", "SCHED-OK", "H AIDI", [
        ("GLAND STEAM CONDENSER VENTING MOTOR", False, "", "H AIDI"),
        ("GLAND STEAM PRESSURE TRANSMITTER 10MAW11CP001", False, "", "H AIDI"),
        ("ACTUATOR GLAND STEAM PRESSURE CONTROL VALVE 10MAW10AA210", False, "", "H AIDI"),
        ("ACTUATOR GLAND STEAM TEMPERATURE CONTROL VALVE 10LCE10AA210", False, "", "H AIDI"),
        ("GENERAL CLEANING", False, "", "H AIDI")
    ]),
    (63, "WO-100826-0074", "OM Y1 EIC UNIT 1 CONVECTIVE PASS", "BOILER", "22/08/2026", "IN PROGRESS", "FERRYUS", [
        ("INSPECTION AND CALIBRATION OXYGEN ANALYZER", True, "22/08/2026", "FERRYUS"),
        ("INLET BACKPASS PRESSURE TRANSMITTER", True, "22/08/2026", "FERRYUS"),
        ("INLET BACKPASS PRESSURE TRANSMITTER", True, "22/08/2026", "FERRYUS"),
        ("INLET BACKPASS PRESSURE TRANSMITTER", True, "22/08/2026", "FERRYUS"),
        ("BACKPASS PRESSURE AFTER LT SH TRANSMITTER", True, "22/08/2026", "FERRYUS"),
        ("BACKPASS PRESSURE AFTER ECO TRANSMITTER", False, "", "FERRYUS")
    ]),
    (64, "WO-100826-0075", "OM Y1 EIC UNIT 1 FLY ASH HANDLING", "ASH HANDLING", "22/08/2026", "IN PROGRESS", "M IQBAL", [
        ("Panel Bapcon - Rapcon Field 1", True, "22/08/2026", "M IQBAL"),
        ("Panel Bapcon - Rapcon Field 2", True, "22/08/2026", "M IQBAL"),
        ("Panel Bapcon - Rapcon Field 3", False, "", "M IQBAL"),
        ("Panel Bapcon - Rapcon Field 4", False, "", "M IQBAL"),
        ("Panel Bapcon - Rapcon Field 5", False, "", "M IQBAL"),
        ("Panel Bapcon - Rapcon Field 6", False, "", "M IQBAL")
    ])
]

wb = openpyxl.load_workbook("Template_Outage_EIC_Monitoring_unit 1.xlsx")

# 1. Update WorkOrder sheet
ws_wo = wb["WorkOrder"]
# Clear existing rows after header
while ws_wo.max_row > 1:
    ws_wo.delete_rows(2)

for item in DATA:
    no, wo_no, job_desc, area, sched, status, pic, subtasks = item
    total_st = len(subtasks)
    done_st = sum(1 for st in subtasks if st[1])
    pct = round((done_st / total_st) * 100, 2) if total_st > 0 else 0
    actual_status = "FINISH" if done_st == total_st and total_st > 0 else ("IN PROGRESS" if done_st > 0 else "SCHED-OK")
    
    ws_wo.append([
        no,                             # Col 1: No
        wo_no,                          # Col 2: No_WO
        1,                              # Col 3: Unit
        job_desc,                       # Col 4: Job_Description
        area,                           # Col 5: Area
        sched,                          # Col 6: Tanggal_Schedule
        sched if done_st > 0 else None, # Col 7: Tanggal_Actual_Start
        sched if done_st == total_st and total_st > 0 else None, # Col 8: Tanggal_Finish
        actual_status,                  # Col 9: Status
        norm_pic(pic),                  # Col 10: PIC
        total_st,                       # Col 11: N_Task
        pct,                            # Col 12: Persen_Progress
        "SUPERVISE, QC, OTHER TASK AS PER EIC JP", # Col 13: Scope
        None,                           # Col 14: Remarks
        None,                           # Col 15: Temuan
        None,                           # Col 16: Tindak_Lanjut
        0                               # Col 17: Jumlah_Foto
    ])

# 2. Update WorkOrder_Checklist sheet
ws_chk = wb["WorkOrder_Checklist"]
while ws_chk.max_row > 1:
    ws_chk.delete_rows(2)

for item in DATA:
    no, wo_no, job_desc, area, sched, status, pic, subtasks = item
    for st in subtasks:
        desc, is_done, dt, st_pic = st
        ws_chk.append([
            wo_no,                      # Col 1: No_WO
            desc,                       # Col 2: Sub_Task_Description
            dt if is_done else None,    # Col 3: Tanggal
            norm_pic(st_pic or pic),    # Col 4: PIC_Task
            is_done,                    # Col 5: Selesai_TRUE_FALSE
            None,                       # Col 6: Temuan
            None,                       # Col 7: Tindak_Lanjut
            0                           # Col 8: Jumlah_Foto
        ])

wb.save("Template_Outage_EIC_Monitoring_unit 1.xlsx")
print(f"Successfully populated {len(DATA)} Work Orders and {ws_chk.max_row - 1} Checklist subtasks into Template_Outage_EIC_Monitoring_unit 1.xlsx!")
